import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import Footer from "./components/footer";
import Navbar from "./components/navbar";
import "./globals.css";
import BodyPaddingCard from "./ui/cards/body-padding";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${font.className} overflow-x-hidden`}>
      <body className="text-lg text-text-primary bg-background">
        <BodyPaddingCard>
          <Navbar className="py-4" />
        </BodyPaddingCard>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
