import type { Metadata } from "next";

import Filters from "./components/filters";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Filters />
        {children}
      </body>
    </html>
  );
}
